services:
  db:
    image: postgres:16
    container_name: refeel-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: refeel-minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 20

  # 初回セットアップ：バケット作成 + CORS設定
  minio-setup:
    image: minio/mc:latest
    container_name: app-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    environment:
      MC_HOST_local: http://${MINIO_ROOT_USER}:${MINIO_ROOT_PASSWORD}@minio:9000
      BUCKET: ${MINIO_BUCKET}
      WEB_ORIGIN: ${WEB_ORIGIN}
    command: >-
      "mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
       mc mb --ignore-existing local/$BUCKET &&
       mc anonymous set none local/$BUCKET &&
       echo '{
         \"CORSRules\": [
           {
             \"AllowedHeaders\": [\"*\"],
             \"AllowedMethods\": [\"GET\",\"PUT\",\"POST\"],
             \"AllowedOrigins\": [\"'\"'\"${WEB_ORIGIN}\"'\"'\"],
             \"ExposeHeaders\": [\"ETag\"],
             \"MaxAgeSeconds\": 3000
           }
         ]
       }' > /tmp/cors.json &&
       mc admin config set local api cors_allow_origin=\"${WEB_ORIGIN}\" &&
       echo \"MinIO bucket & CORS configured\" && sleep 2"
    restart: "no"

volumes:
  pg:
  minio:
